### ISSUE TITLE
Crashes server if "awards" is not installed

### ISSUE THREAD

**Issue by Arcitec** [mt-historical/i3#24]
- Latest version of VoxeLibre + i3 as of this writing.
- Clicking the "awards" tab of inventory crashes the server with some lua error about trying to access "awards".

It's easy to reproduce: Just run it, click Awards, and it will crash.

Installing "awards" fixes the crash but is not appropriate on servers that don't want the awards mod. Especially since the other tabs show a sane "skinsdb is not installed" instead.

Edit: The bug does not happen with Minetest Game. Only when the game mode is VoxeLibre.

**Comment by wsor4035** [comment]
this is because mineclone2/voxelibre is using an ancient version of awards internally, they should either update it like [mineclonia did](https://codeberg.org/mineclonia/mineclonia/commit/5d9f32ffdcea8cd78ae36ae85e4bdcca540ca42a) or rename the global to something else. you should file an issue with then

**Comment by Arcitec** [comment]
@wsor4035 Ah okay, thank you for the valuable information! :)
